---
- hosts: server
  become: true
  name: Install MySQL fedora
  handlers:
    - name: restart mysql
      ansible.builtin.service:
        name: mysql
        state: restarted
        enabled: true
  tasks:
    - name: Update system pkgs, install mysql-server and python3-pip
      ansible.builtin.apt:
        pkg:
          - mysql-server
          - python3-pip
        state: latest
        update_cache: true
    - name: Install mysql dependencies (PyMySQL)
      ansible.builtin.pip:
        name:
          - PyMySQL
    - name: Create database for wordpress 
      community.mysql.mysql_db:
        name:
          - wpdb
        state: present
        login_unix_socket: /var/run/mysqld/mysqld.sock
    - name: Create user for wordpress db
      community.mysql.mysql_user:
        name: wpuser
        password: 1234
        priv: 'wpdb.*:ALL'
        state: present
        login_unix_socket: /var/run/mysqld/mysqld.sock
        column_case_sensitive: false
      notify: restart mysql